In [124]:
import pandas as pd
import numpy as np

In [58]:
data = pd.read_csv(open("/Volumes/FLASH/KDML105-1400_PTT1-1402_RD6-1401_train.txt",'r'), sep="\t", header=None) 

In [140]:
data[0][0]

'0 1:283997.000000 2:3010.733309 3:312.000000 4:1190.816946 5:0.393712 6:0.254996 7:17.425668 8:0.057387 9:0.004193 10:0.000168 11:0.254996 12:0.973250 13:-0.034861 14:0.290076 15:0.083969 16:0.000000 17:-0.007634 18:0.000000 19:0.007634 20:-0.076336 21:-0.022989 22:0.158367 23:-0.328244 24:-0.106870 25:-0.015267 26:-0.007634 27:0.022901 28:0.236641 29:0.587786 30:1.096862 31:0.178571 32:-0.035714 33:-0.178571 34:0.035714 35:-0.107143 36:-0.285714 37:0.107143 38:0.535714 39:0.482143 40:0.464286 41:0.473214 42:0.478571 43:0.464286 44:0.443878 45:0.892857 46:1.392857 47:1.535714 48:1.035714 49:0.535714 50:0.571429 51:0.571429 52:0.477442 53:3157.759624 54:733.535401 55:4.240168 56:0.414824 57:-0.000042 58:-0.100773 59:0.000035 60:0.016763 61:0.029462 62:0.022836 63:0.013240 64:0.021374 65:0.013508 66:0.025347 67:0.022692 68:0.039745 69:0.002061 70:0.004115 71:0.002817 72:0.019779 73:0.004121 74:0.005234 75:0.016345 76:0.031839 77:0.011789 78:0.004421 79:0.010976 80:0.019268 81:0.027605 8

In [114]:
def split_text(text):
    feature = []
    label = text.split(' ')[0]
    for i in list(filter(None, text.split(' ')[1:])):
        feature.append(i.split(':')[1])
    return label,feature

In [127]:
labels = []
features = []
for i in range(len(data)):
    label, feature = split_text(data[0][i])
    labels.append(label)
    features.append(feature)


array([[  2.83997000e+05,   3.01073340e+03,   3.12000000e+02, ...,
          1.75118317e+02,   1.99249847e+02,   1.76084213e+02],
       [  3.03885500e+05,   3.39556885e+03,   3.32000000e+02, ...,
          1.93707306e+02,   2.06683197e+02,   1.79357452e+02],
       [  3.03187000e+05,   3.13727759e+03,   3.17000000e+02, ...,
          1.84575012e+02,   2.05704468e+02,   1.76938324e+02],
       ..., 
       [  2.94155000e+05,   2.86159619e+03,   3.36000000e+02, ...,
          1.32133194e+02,   1.82727951e+02,   1.73913208e+02],
       [  2.84005000e+05,   2.96867432e+03,   3.36000000e+02, ...,
          1.64854675e+02,   2.07724854e+02,   1.82470993e+02],
       [  2.99449500e+05,   2.99778003e+03,   3.34000000e+02, ...,
          1.45342957e+02,   1.91120010e+02,   1.77895950e+02]], dtype=float32)

In [130]:
features = np.array(features, dtype=np.float32)

In [142]:
features[0]

array([  2.83997000e+05,   3.01073340e+03,   3.12000000e+02,
         1.19081689e+03,   3.93712014e-01,   2.54996002e-01,
         1.74256687e+01,   5.73870018e-02,   4.19300003e-03,
         1.67999999e-04,   2.54996002e-01,   9.73249972e-01,
        -3.48609984e-02,   2.90075988e-01,   8.39689970e-02,
         0.00000000e+00,  -7.63399992e-03,   0.00000000e+00,
         7.63399992e-03,  -7.63359964e-02,  -2.29889993e-02,
         1.58366993e-01,  -3.28244001e-01,  -1.06870003e-01,
        -1.52669996e-02,  -7.63399992e-03,   2.29010005e-02,
         2.36641005e-01,   5.87786019e-01,   1.09686196e+00,
         1.78571001e-01,  -3.57140005e-02,  -1.78571001e-01,
         3.57140005e-02,  -1.07143000e-01,  -2.85714000e-01,
         1.07143000e-01,   5.35713971e-01,   4.82143015e-01,
         4.64286000e-01,   4.73214000e-01,   4.78570998e-01,
         4.64286000e-01,   4.43877995e-01,   8.92857015e-01,
         1.39285696e+00,   1.53571403e+00,   1.03571403e+00,
         5.35713971e-01,

In [131]:
from sklearn.model_selection import train_test_split
text_train, text_test, sent_train, sent_test = train_test_split(features, labels, test_size = 0.30, random_state = 40)


In [134]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score
from sklearn.multiclass import OneVsRestClassifier
from sklearn.metrics import confusion_matrix
from sklearn.metrics import precision_recall_fscore_support
from sklearn.metrics import precision_score
from sklearn.metrics import recall_score
from sklearn.metrics import f1_score
from sklearn.metrics import classification_report

logreg = LogisticRegression()
logreg.fit(text_train, sent_train)
y_pred = logreg.predict(text_test)
print('Testing accuracy %s' % accuracy_score(sent_test, y_pred))
print('Testing F1 score: {}'.format(f1_score(sent_test, y_pred, average='weighted')))
cm_log = confusion_matrix(sent_test, y_pred)
print(cm_log)
print('log')
print(classification_report(sent_test, y_pred, labels=list(set(sent_test)), target_names=['NEGATIVE', 'POSITIVE']))


/Users/3arthzneiz/anaconda3/lib/python3.6/site-packages/sklearn/linear_model/logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
/Users/3arthzneiz/anaconda3/lib/python3.6/site-packages/sklearn/linear_model/logistic.py:469: FutureWarning: Default multi_class will be changed to 'auto' in 0.22. Specify the multi_class option to silence this warning.
  "this warning.", FutureWarning)


Testing accuracy 0.90959555908
Testing F1 score: 0.9091742875953261
[[357  57  10]
 [ 40 367   2]
 [  5   0 423]]
log
              precision    recall  f1-score   support

    NEGATIVE       0.89      0.84      0.86       424
    POSITIVE       0.87      0.90      0.88       409

    accuracy                           0.91      1261
   macro avg       0.91      0.91      0.91      1261
weighted avg       0.91      0.91      0.91      1261



/Users/3arthzneiz/anaconda3/lib/python3.6/site-packages/sklearn/metrics/classification.py:1870: UserWarning: labels size, 3, does not match size of target_names, 2
  .format(len(labels), len(target_names))


In [143]:
logreg.coef_

array([[ -2.45220100e-05,   5.64252714e-03,   1.06291252e-02,
         -6.05639339e-03,  -7.28436237e-05,  -4.82817039e-05,
         -1.24962625e-03,  -4.06754750e-06,  -3.42383476e-07,
         -5.31081873e-08,  -4.82817039e-05,  -1.71768011e-04,
          1.97763038e-04,  -2.53948656e-04,  -4.10482493e-04,
         -7.27399831e-05,  -1.45567547e-04,  -2.03168094e-05,
          3.01298283e-04,   1.63202710e-04,   2.91722894e-03,
          2.19480693e-04,  -4.49080338e-04,   3.45193803e-04,
          1.39409252e-05,   1.22314114e-04,   1.10699796e-04,
         -1.78595511e-04,  -7.15216189e-04,   7.64596173e-07,
          9.29675520e-04,   5.46946153e-03,   2.10970979e-03,
         -1.03076976e-04,   1.56834935e-04,   1.18706011e-04,
          1.57777780e-04,   1.67060932e-03,   3.38741287e-03,
          2.87119908e-03,   1.76691945e-03,   1.51559152e-03,
          1.07203978e-03,   7.12041545e-04,   7.83571646e-03,
          3.77190084e-03,   2.10323137e-03,  -1.00577334e-04,
        