In [2]:
import numpy as np

input_text = ["duct", "tape", "work", "anywher", "magic", "worship"]

In [5]:
np.random.seed(42)
# one-hotencoding
input_array_tape = np.array([0,1,0,0,0,0]) #"tape"

# weight input 6*3 metric
input_weight_matrix = np.random.random_sample((6,3))
print(input_weight_matrix)

[[0.37454012 0.95071431 0.73199394]
 [0.59865848 0.15601864 0.15599452]
 [0.05808361 0.86617615 0.60111501]
 [0.70807258 0.02058449 0.96990985]
 [0.83244264 0.21233911 0.18182497]
 [0.18340451 0.30424224 0.52475643]]


In [6]:
# hidden layer
projection = np.dot(input_array_tape,input_weight_matrix)
print(projection)

[0.59865848 0.15601864 0.15599452]


In [7]:
# assume that window size = 5
# so this will random weight for w(t-2) behind the input 2 word
# weight output 3*6 
output_weight_matrix = np.random.random_sample((3,6))
print(output_weight_matrix)

[[0.43194502 0.29122914 0.61185289 0.13949386 0.29214465 0.36636184]
 [0.45606998 0.78517596 0.19967378 0.51423444 0.59241457 0.04645041]
 [0.60754485 0.17052412 0.06505159 0.94888554 0.96563203 0.80839735]]


In [8]:
# hidden layer mul with output weight
output_array_for_input_tape_and_orange_output_context = np.dot(projection, output_weight_matrix)
print(output_array_for_input_tape_and_orange_output_context)

[0.42451664 0.32344971 0.40759145 0.31176029 0.41795589 0.35267831]


In [10]:
print(list(zip(input_text, output_array_for_input_tape_and_orange_output_context)))

[('duct', 0.42451663675598933), ('tape', 0.3234497105099373), ('work', 0.4075914505752598), ('anywher', 0.3117602853605092), ('magic', 0.41795589389125587), ('worship', 0.35267831257488347)]


In [ ]:
# pass to softmax ....